import type { AppSettings } from "./types";

export const ROBLOX_DISCOVERY_CHARTS = [
  "top-trending",
  "up-and-coming",
  "top-playing-now",
  "fun-with-friends",
  "top-revisited",
  "trending-in-simulation",
  "trending-in-survival",
  "trending-in-action",
  "trending-in-rpg",
  "trending-in-shooter",
  "trending-in-strategy",
  "trending-in-sports-and-racing",
  "trending-in-roleplay-and-avatar-sim",
  "trending-in-party-and-casual",
  "trending-in-obby-and-platformer",
  "trending-in-puzzle",
  "trending-in-shopping",
  "trending-in-entertainment",
  "top-rated",
  "most-popular",
  "top-paid-access",
  "top-earning",
] as const;

export const LEGACY_ROBLOX_CHARTS = ["top-trending", "up-and-coming", "top-playing-now"] as const;

export const COLLECTION_DISCOVERY_CONFIG = {
  recentGameTrackingDays: 90,
  activeGameTrackingDays: 30,
  activeGameMinimumCcu: 100,
  maximumTrackedGames: 3_000,
  maximumSearchKeywords: 6,
  maximumRecommendationSeeds: 5,
  searchResultsPerKeyword: 40,
  recommendationsPerSeed: 20,
} as const;

export const ROBLOX_EVENT_MARKERS = ["[upd", "[update", "event", "2x", "x2", "admin abuse"] as const;

export const DEFAULT_SETTINGS: AppSettings = {
  thresholds: {
    minimumBaselineCcu: 25,
    minimumAbsoluteGain: 50,
    breakoutMomentum: 68,
    saturationMinGames: 6,
    saturationNewGames7d: 3,
    saturationFlatGrowth: 12,
    hourlyRetentionDays: 30,
  },
  momentumWeights: {
    ccuGrowth: 28,
    acceleration: 14,
    absoluteGain: 18,
    visitGrowth: 10,
    rankImprovement: 10,
    freshness: 10,
    persistence: 10,
  },
  opportunityWeights: {
    trendStrength: 24,
    differentiation: 16,
    feasibility: 18,
    mobileClarity: 10,
    reusePotential: 12,
    retention: 12,
    durability: 8,
  },
  collection: {
    intervalMinutes: 30,
    country: process.env.ROBLOX_COUNTRY || "all",
    device: process.env.ROBLOX_DEVICE || "computer",
    charts: [...ROBLOX_DISCOVERY_CHARTS],
    rolimonsEnabled: process.env.ROLIMONS_ENABLED !== "false",
    rolimonsCandidates: 20,
  },
  taxonomy: {
    coreLoop: [
      { tag: "Idle", aliases: ["idle", "afk"] },
      { tag: "Tycoon", aliases: ["tycoon", "factory"] },
      { tag: "Obby", aliases: ["obby", "escape", "parkour", "tower"] },
      { tag: "Survival", aliases: ["survival", "survive"] },
      { tag: "Collection", aliases: ["collect", "collection", "collector"] },
      { tag: "Combat", aliases: ["combat", "battle", "fighter", "battleground"] },
      { tag: "RNG", aliases: ["rng", "random"] },
      { tag: "Steal", aliases: ["steal", "theft", "rob"] },
      { tag: "Defense", aliases: ["defense", "defence", "tower defense"] },
    ],
    progression: [
      { tag: "+1 per second", aliases: ["+1", "per second", "every second"] },
      { tag: "Training", aliases: ["training", "train", "workout"] },
      { tag: "Grow", aliases: ["grow", "growing", "garden"] },
      { tag: "Upgrade", aliases: ["upgrade", "level up"] },
      { tag: "Rebirth", aliases: ["rebirth", "prestige"] },
      { tag: "Merge", aliases: ["merge", "combine"] },
    ],
    reward: [
      { tag: "Lucky Block", aliases: ["lucky block", "luck block"] },
      { tag: "Egg", aliases: ["egg", "hatch"] },
      { tag: "Chest", aliases: ["chest", "crate"] },
      { tag: "Roll", aliases: ["roll", "spin"] },
      { tag: "Mutation", aliases: ["mutation", "mutate", "mutant"] },
    ],
    social: [
      { tag: "Tsunami", aliases: ["tsunami", "flood", "wave"] },
      { tag: "Raid", aliases: ["raid", "boss"] },
      { tag: "Theft", aliases: ["steal", "theft", "rob"] },
      { tag: "Race", aliases: ["race", "racing"] },
      { tag: "Defense", aliases: ["defense", "defence", "protect"] },
      { tag: "Cooperation", aliases: ["co-op", "coop", "together", "team up"] },
    ],
    theme: [
      { tag: "Monkey", aliases: ["monkey", "ape", "gorilla"] },
      { tag: "Kitty", aliases: ["kitty", "kitten", "cat"] },
      { tag: "Brainrot", aliases: ["brainrot", "brain rot", "skibidi"] },
      { tag: "Anime", aliases: ["anime", "manga", "ninja"] },
      { tag: "Kawaii", aliases: ["kawaii", "cute", "pastel"] },
      { tag: "Horror", aliases: ["horror", "scary", "nightmare", "backrooms"] },
      { tag: "Animals", aliases: ["animal", "pet", "zoo"] },
    ],
  },
  developerProfile: {
    teamSize: 1,
    robloxExperience: "recent",
    webProductSkill: 5,
    uiUxSkill: 5,
    budget: "limited",
    preferredWeeksMin: 2,
    preferredWeeksMax: 4,
    mobileFirst: true,
    prefersClearLoops: true,
    reusableSystems: ["simulator", "tycoon"],
  },
  discordWebhook: process.env.DISCORD_WEBHOOK_URL || "",
};

export const STAGE_LABELS = {
  spark: "Spark",
  emerging: "Emerging",
  expanding: "Expanding",
  copy_wave: "Copy wave",
  saturated: "Saturated",
  declining: "Declining",
} as const;

export const IDEA_EVIDENCE_CONFIG = {
  recentGameMaxAgeDays: 90,
  minimumHistoryHours: 20,
  minimumCurrentCcu: 5_000,
  minimumGain24h: 1_000,
  minimumGrowth24h: 15,
  minimumNewVisits24h: 100_000,
  strongGrowth24h: 100,
  strongGain24h: 6_000,
  strongNewVisits24h: 1_000_000,
  strongRankMovement24h: 20,
  maximumSupportingGames: 4,
  durability: {
    minimumHours: 72,
    strongHours: 168,
    dailyWindowToleranceHours: 3,
    minimumPositiveDailyWindows: 2,
    minimumDailyGain: 500,
    minimumDailyGrowth: 5,
    durableMaximumPeakDrawdown: 25,
    fragilePeakDrawdown: 35,
    fragileDailyReversal: -20,
    eventMarkers: ROBLOX_EVENT_MARKERS,
  },
  evidenceWeights: {
    momentum: 25,
    freshness: 15,
    growth24h: 20,
    gain24h: 15,
    newVisits24h: 10,
    rankMovement24h: 10,
    persistence: 5,
  },
  recommendationWeights: {
    algorithmEvidence: 30,
    durability: 15,
    proofBreadth: 15,
    trendOpportunity: 15,
    lowSaturation: 10,
    soloFit: 15,
  },
} as const;
