"use client";

import { Save } from "lucide-react";
import { useState } from "react";
import type { AppSettings } from "@/lib/types";

export function SettingsForm({ initialSettings }: { initialSettings: AppSettings }) {
  const [settings, setSettings] = useState(initialSettings);
  const [taxonomy, setTaxonomy] = useState(JSON.stringify(initialSettings.taxonomy, null, 2));
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  function setNested(section: keyof AppSettings, key: string, value: unknown) {
    setSettings((current) => ({ ...current, [section]: { ...(current[section] as object), [key]: value } }));
  }
  async function save() {
    setSaving(true);
    setMessage("");
    try {
      const value = { ...settings, taxonomy: JSON.parse(taxonomy) };
      const response = await fetch("/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) });
      const result = await response.json() as { error?: string };
      setMessage(response.ok ? "Settings saved. Run analysis again to apply scoring or taxonomy changes." : result.error || "Settings could not be saved.");
    } catch {
      setMessage("Taxonomy JSON is invalid.");
    } finally {
      setSaving(false);
    }
  }
  return <div className="grid"><div className="settings-grid"><section className="card settings-section"><h2>Detection thresholds</h2><p>Small-denominator protection and stage boundaries.</p><div className="settings-fields"><NumberField label="Minimum baseline CCU" value={settings.thresholds.minimumBaselineCcu} onChange={(value) => setNested("thresholds", "minimumBaselineCcu", value)} /><NumberField label="Minimum absolute gain" value={settings.thresholds.minimumAbsoluteGain} onChange={(value) => setNested("thresholds", "minimumAbsoluteGain", value)} /><NumberField label="Breakout momentum" value={settings.thresholds.breakoutMomentum} onChange={(value) => setNested("thresholds", "breakoutMomentum", value)} /><NumberField label="Saturation game count" value={settings.thresholds.saturationMinGames} onChange={(value) => setNested("thresholds", "saturationMinGames", value)} /><NumberField label="New games for saturation" value={settings.thresholds.saturationNewGames7d} onChange={(value) => setNested("thresholds", "saturationNewGames7d", value)} /><NumberField label="Flat demand ceiling (%)" value={settings.thresholds.saturationFlatGrowth} onChange={(value) => setNested("thresholds", "saturationFlatGrowth", value)} /><NumberField label="Hourly retention (days)" value={settings.thresholds.hourlyRetentionDays} onChange={(value) => setNested("thresholds", "hourlyRetentionDays", value)} /></div></section>
      <section className="card settings-section"><h2>Momentum weights</h2><p>Weights are normalized, so they do not need to add to 100.</p><div className="settings-fields">{Object.entries(settings.momentumWeights).map(([key, value]) => <NumberField key={key} label={humanize(key)} value={value} onChange={(next) => setNested("momentumWeights", key, next)} />)}</div></section>
      <section className="card settings-section"><h2>Opportunity weights</h2><p>Keep opportunity separate from raw market momentum.</p><div className="settings-fields">{Object.entries(settings.opportunityWeights).map(([key, value]) => <NumberField key={key} label={humanize(key)} value={value} onChange={(next) => setNested("opportunityWeights", key, next)} />)}</div></section>
      <section className="card settings-section"><h2>Collection</h2><p>Collection runs hourly and remains idempotent within each one-hour bucket.</p><div className="settings-fields"><NumberField label="Rolimon's candidates" value={settings.collection.rolimonsCandidates} onChange={(value) => setNested("collection", "rolimonsCandidates", value)} /><TextField label="Country" value={settings.collection.country} onChange={(value) => setNested("collection", "country", value)} /><TextField label="Device" value={settings.collection.device} onChange={(value) => setNested("collection", "device", value)} /><div className="field wide"><label><input type="checkbox" checked={settings.collection.rolimonsEnabled} onChange={(event) => setNested("collection", "rolimonsEnabled", event.target.checked)} /> Enable Rolimon&apos;s discovery</label></div><TextField wide label="Chart IDs (comma-separated)" value={settings.collection.charts.join(", ")} onChange={(value) => setNested("collection", "charts", value.split(",").map((item) => item.trim()).filter(Boolean))} /></div></section>
      <section className="card settings-section"><h2>Developer profile</h2><p>Feasibility is scored against this profile, not an imaginary full studio.</p><div className="settings-fields"><NumberField label="Team size" value={settings.developerProfile.teamSize} onChange={(value) => setNested("developerProfile", "teamSize", value)} /><div className="field"><label htmlFor="roblox-experience">Roblox experience</label><select className="select" id="roblox-experience" value={settings.developerProfile.robloxExperience} onChange={(event) => setNested("developerProfile", "robloxExperience", event.target.value)}><option value="recent">Recent</option><option value="intermediate">Intermediate</option><option value="expert">Expert</option></select></div><div className="field"><label htmlFor="budget">Budget</label><select className="select" id="budget" value={settings.developerProfile.budget} onChange={(event) => setNested("developerProfile", "budget", event.target.value)}><option value="limited">Limited</option><option value="moderate">Moderate</option><option value="high">High</option></select></div><NumberField label="Minimum weeks" value={settings.developerProfile.preferredWeeksMin} onChange={(value) => setNested("developerProfile", "preferredWeeksMin", value)} /><NumberField label="Maximum weeks" value={settings.developerProfile.preferredWeeksMax} onChange={(value) => setNested("developerProfile", "preferredWeeksMax", value)} /><NumberField label="Web/product skill (1–5)" value={settings.developerProfile.webProductSkill} onChange={(value) => setNested("developerProfile", "webProductSkill", value)} /><NumberField label="UI/UX skill (1–5)" value={settings.developerProfile.uiUxSkill} onChange={(value) => setNested("developerProfile", "uiUxSkill", value)} /><TextField label="Reusable systems" value={settings.developerProfile.reusableSystems.join(", ")} onChange={(value) => setNested("developerProfile", "reusableSystems", value.split(",").map((item) => item.trim()).filter(Boolean))} /><div className="field"><label><input type="checkbox" checked={settings.developerProfile.mobileFirst} onChange={(event) => setNested("developerProfile", "mobileFirst", event.target.checked)} /> Mobile-first</label></div><div className="field"><label><input type="checkbox" checked={settings.developerProfile.prefersClearLoops} onChange={(event) => setNested("developerProfile", "prefersClearLoops", event.target.checked)} /> Prefer immediately clear loops</label></div></div></section>
      <section className="card settings-section"><h2>Delivery</h2><p>The webhook is used by daily reports and collection-health alerts. Repeated event keys are suppressed.</p><div className="settings-fields"><div className="field wide"><label htmlFor="discordWebhook">Discord webhook</label><input className="input" type="password" id="discordWebhook" value={settings.discordWebhook} onChange={(event) => setSettings((current) => ({ ...current, discordWebhook: event.target.value }))} placeholder="https://discord.com/api/webhooks/…" /></div></div></section>
    </div>
    <section className="card settings-section"><h2>Taxonomy and aliases</h2><p>Edit the five independent dimensions as JSON. Each tag accepts multiple aliases; analysis uses case-insensitive whole phrase matching.</p><textarea className="textarea" style={{ minHeight: 430, fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 11 }} value={taxonomy} onChange={(event) => setTaxonomy(event.target.value)} spellCheck={false} /></section>
    <div className="form-actions">{message ? <span className="trend-meta">{message}</span> : null}<button className="button primary" onClick={save} disabled={saving}><Save size={14} />{saving ? "Saving…" : "Save settings"}</button></div>
  </div>;
}

function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { const id = label.toLowerCase().replace(/[^a-z0-9]+/g, "-"); return <div className="field"><label htmlFor={id}>{label}</label><input className="input" id={id} type="number" value={value} onChange={(event) => onChange(Number(event.target.value))} /></div>; }
function TextField({ label, value, onChange, wide = false }: { label: string; value: string; onChange: (value: string) => void; wide?: boolean }) { const id = label.toLowerCase().replace(/[^a-z0-9]+/g, "-"); return <div className={`field ${wide ? "wide" : ""}`}><label htmlFor={id}>{label}</label><input className="input" id={id} value={value} onChange={(event) => onChange(event.target.value)} /></div>; }
function humanize(value: string) { return value.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/^./, (letter) => letter.toUpperCase()); }
